name: OWASP ZAP Scan

on:
  push:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Subir aplicação
        run: docker run -d -p 8080:80 nginx

      - name: Esperar aplicação iniciar
        run: sleep 20

      - name: Rodar ZAP Baseline Scan
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 \
            -r zap-report.html

      - name: Verificar arquivos gerados
        run: ls -la

      - name: Upload relatório ZAP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html