name: OWASP ZAP Scan

on:
  push:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Subir aplicação
        run: |
          docker run -d --name app -p 8080:80 nginx
          sleep 15

      - name: Verificar app
        run: curl http://localhost:8080

      - name: Rodar ZAP
        run: |
         docker run --rm \
         -v $(pwd):/zap/wrk/:rw \
         ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
         -t http://localhost:8080 \
         -r zap-report.html
      - name: Verificar arquivo gerado
        run: ls -la

      - name: Upload relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html